# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


title: TaeYoung Kim
description: >- # this means to ignore newlines until "baseurl:"
  TaeYoung Kim
baseurl: "" # the subpath of the site
url: "https://tykimNWO.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: tykim75@yonsei.ac.kr
      link: mailto:tykim75@yonsei.ac.kr
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/%ED%83%9C%EC%98%81-%EA%B9%80-314b5a283/
    - name: GitHub
      link: http://github.com/tykimNWO

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
